### PR TITLE
improves time readability

### LINKED ISSUE #53: Improve times readability
Need a function to convert time and improve user readability for big cubes example 93.03s to 1:33.03

### PR DESCRIPTION
**Pull request by diwash007**
fixes #53

### CODE REVIEW

**Comment by diwash007** [comment]
fixes #53

**Review by bryanlundberg — CHANGES_REQUESTED** [review]
@diwash007 This appears to be exactly what I was searching for. I have a minor request for a small adjustment. Instead of displaying the time as "02.59," could you please display it as "2.59"? Similarly, for "02:59.28," could you show it as "2:59.28"? 👌

**Comment by diwash007** [comment]
> @diwash007 This appears to be exactly what I was searching for. I have a minor request for a small adjustment. Instead of displaying the time as "02.59," could you please display it as "2.59"? Similarly, for "02:59.28," could you show it as "2:59.28"? 👌

done

**Review by bryanlundberg — APPROVED** [review]
an exceptional job, thanks!

**Pull request merged**
