### PR TITLE
added ability for users to select initial cube by default

### PR DESCRIPTION
**Pull request by myheadisempty**
**What does this PR do?**
feat #328

**Related Issue(s)**
none

**Changes**
- Added a new section on Settings named "Preferences".
- Implemented the ability to select and save a default starting cube.
- Added translation into English and Russian for labels.
- Included the necessary logic to load the default cube on startup.
- Updated dropdown to include a "None" option for cube selection.

**Additional Comments**
Please review and suggest some optimization can be made.

**By submitting this PR, I confirm that:**
- [x] I have reviewed my code and believe it is ready for merging.
- [x] I understand that this PR may be subject to review and changes.
- [x] I agree to abide by the code of conduct and contributing guidelines of this project.

### CODE REVIEW

**Review by bryanlundberg — CHANGES_REQUESTED** [review]
I was not able to verify your changes, does not compile.

image

I hope you could fix it. Thanks!

**Comment by myheadisempty** [comment]
Fixed it, it should work now!

**Comment by bryanlundberg** [comment]
There's an issue with trying to close the menu by clicking outside there.

image

**Comment by bryanlundberg** [comment]
Name should be truncated if it's very long.

image

**Comment by bryanlundberg** [comment]
Current:
image

The selected cube should be highlighted:
image

**Comment by myheadisempty** [comment]
Check it out

**Comment by bryanlundberg** [comment]
Hi @myheadisempty I helped you with minor CSS styling to match menu section colors schema.

I also refactor the component <MenuSelectDefaultStartCube /> separing the preferences section, for sure we will add more customizable options.

**Pull request merged**
