### PR TITLE
Full Screen functionality

### PR DESCRIPTION
**Pull request by RigvedRocks**
**What does this PR do?**
I have added the functionality for the full-screen feature as outlined in https://github.com/bryanlundberg/NexusTimer/issues/202

**Changes**
I have added the full-screen feature to the project. In this I have made modifications to the following files and folders -
i) Added two new files in the Icon folder for full-screen and exit full-screen icons - FullScreen.tsx and ExitFullScreen.tsx
ii) Made changes to the HeaderTimer.tsx
iii) Created a custom hook called useFullScreen under the hooks directory.

**Screenshots or GIFs (if applicable)**
Screenshot (104)
Screenshot (105)

**By submitting this PR, I confirm that:**
- [x] I have reviewed my code and believe it is ready for merging.
- [x] I understand that this PR may be subject to review and changes.
- [x] I agree to abide by the code of conduct and contributing guidelines of this project.

### CODE REVIEW

**Review by bryanlundberg — CHANGES_REQUESTED** [review]
Unfortunately, the code does not compile

```
./src/hooks/useFullScreen.ts:31:26
Type error: Property 'mozRequestFullScreen' does not exist on type 'HTMLElement'. Did you mean 'requestFullscreen'?

  29 |       if (element.requestFullscreen) {
  30 |         element.requestFullscreen();
> 31 |       } else if (element.mozRequestFullScreen) {
     |                          ^
  32 |         element.mozRequestFullScreen();
  33 |       } else if (element.webkitRequestFullscreen) {
  34 |         element.webkitRequestFullscreen();
```

**Comment by RigvedRocks** [comment]
In my case, it is getting compiled and I am getting the desired result in the browser.
Screenshot (106)
Screenshot (107)

**Comment by bryanlundberg** [comment]
In development mode, the interface remains visible even in the presence of errors. 

Execute `npm run build` to render the application in production mode.

**Comment by RigvedRocks** [comment]
Hey, I have resolved the issue. Please check and get back to me.

**Comment by bryanlundberg** [comment]
> Hey, I have resolved the issue. Please check and get back to me.

Sure, commit

**Comment by RigvedRocks** [comment]
Done.Please have a look at it.

**Review by bryanlundberg — COMMENTED** [review]
Oh @RigvedRocks it seems like the interface is broken again. I previously assisted you in fixing it, but it appears that the old UI has been committed, overwriting the improvements we made.

image

image

There other issue: when navigating between pages in fullscreen mode and then returning to the main page, the icon resets to the Fullscreen icon instead of persisting as an Exit FullScreen icon in its status.

😢

**Comment by bryanlundberg** [comment]
I will implement the necessary fixes and credit you as a coauthor. Thank you for your collaboration!

**Comment by RigvedRocks** [comment]
Sorry for the trouble, @bryanlundberg. If you need any assistance, feel free to ping me. I look forward to contributing more to the project. Thank you for the credit, appreciate that.

**Pull request closed without merging**
