### PR TITLE
Feat/custom context menu

### LINKED ISSUE #270: custom menu context
Right-click should display a submenu with quick action options

- Active "solve" should change border color for better UX.
- Submenu should be fixed down,  width 100% of "solve" size. (Fits better instead using right click x,y position state)

sample:
image

### PR DESCRIPTION
**Pull request by syrok94**
**What does this PR do?**
fix #270, add a context menu as well as fix its position

**Related Issue(s)**
none

**Changes**
Added a ContextMenu.tsx file which can be reused to add a context menu

**Screenshots or GIFs (if applicable)**
n1

**Additional Comments**
none

**By submitting this PR, I confirm that:**
- [x] I have reviewed my code and believe it is ready for merging.
- [x] I understand that this PR may be subject to review and changes.
- [x] I agree to abide by the code of conduct and contributing guidelines of this project.

### CODE REVIEW

**Review by bryanlundberg — CHANGES_REQUESTED** [review]
Hi @syrok94  I think you are taking a more complicated approach than necessary. Anyway, I found another issue.

- Menu lost position at scroll

0e0240ae21fa02e7882e0672cdafc60a

- Last solves imposible use menu
image

- Its missing the 100% width
image

- Font size, its too big

- Black theme its not correct the text color
image


👋

**Comment by syrok94** [comment]
Hi @bryanlundberg , will you please tell me the simplified way of doing this so that I can try it that way?

**Comment by bryanlundberg** [comment]
Hey @syrok94 I carefully reviewed your implementation and it was fine. I helped you with some minor adjustments to the menu's positioning and styling, it was easier than explaining 😅

This feature looks ready to go, thanks for your work!

**Comment by bryanlundberg** [comment]
Preview

styled: Positioning / Colors / Size

https://github.com/bryanlundberg/NexusTimer/assets/119996547/3a756079-7229-4a3c-90b0-9dc622285cfe

**Review by bryanlundberg — APPROVED** [review]

**Pull request merged**
