### PR TITLE
Format time

### LINKED ISSUE #79: Time Display Formatting
We got a new function for formatting time in a nice way. As a result, we need update all existing components to utilize this function before rendering.

- Timer (desviation, mean, best, ao5 - ao100)
- Solves (session / all, solve modal)
- Metrics (Last activity, all category statistics...)

[formatTime.ts](https://github.com/bryanlundberg/NexusTimer/blob/main/src/lib/formatTime.ts)

### PR DESCRIPTION
**Pull request by abishek0057**
fix #79

### CODE REVIEW

**Review by bryanlundberg — CHANGES_REQUESTED** [review]
The result is exactly what I need, but I have a few minor requests to optimize it further. I also noticed that the 'format best time' is missing in CategoryStatistics.tsx. If you have some free time to address these, that would be greatly appreciated.

@abishek0057 👋

**Comment by abishek0057** [comment]
@bryanlundberg, would returning the mean and deviation in milliseconds instead of using "/ 1000" as it currently does pose any issues in other calculations and charts data? Since I am not familiar with the entire calculation, I haven't made changes to the base function for now. I'm ready to proceed according to your instructions.

**Comment by bryanlundberg** [comment]
> @bryanlundberg, would returning the mean and deviation in milliseconds instead of using "/ 1000" as it currently does pose any issues in other calculations and charts data? Since I am not familiar with the entire calculation, I haven't made changes to the base function for now. I'm ready to proceed according to your instructions.

Should not affect nothing, the plan is move all data to ms, `formatTime()` will make the job displaying whatever value anywhere.

**Comment by abishek0057** [comment]
@bryanlundberg changes have been made. Ready for re-review

**Review by bryanlundberg — APPROVED** [review]
This looks great and is good to go. Thanks for your hard work on this. 👌

**Comment by abishek0057** [comment]
@bryanlundberg can you please add hacktoberfest label to this repository or label my PR as hacktoberfest-accepted

**Comment by bryanlundberg** [comment]
> @bryanlundberg can you please add hacktoberfest label to this repository or label my PR as hacktoberfest-accepted

Done

**Comment by abishek0057** [comment]
Could you please add the 'hacktoberfest' label to the repository? This would be very helpful for my Hacktoberfest journey, as it would eliminate the need to label each PR as 'hacktoberfest-accepted.

**Comment by bryanlundberg** [comment]
better idea, done. 👌

**Comment by abishek0057** [comment]
@bryanlundberg, I noticed that the deviation and mean values are too large. Upon checking the file, I realized that I forgot to remove `/ 1000` from the [OverviewPanel.tsx](https://github.com/bryanlundberg/NexusTimer/blob/main/src/components/OverviewPanel.tsx) file while fixing issue #89.
image
How do I proceed? Do I need to create a new issue, make the change, and then create the PR, or can I directly make the change and create the PR?

**Comment by bryanlundberg** [comment]
You can just create the PR, it's fine.

**Pull request merged**
