### PR TITLE
Confirm Deletion

### PR DESCRIPTION
**Pull request by Adimaniac31**
**What does this PR do?**
This PR creates a dialog box to confirm the deletion of cube by mentioning the number of solves.

**Related Issue(s)**
issue #122
 
**Changes**
I have made changes in Modal.tsx and useModalCube.ts by creating some more functions.

**Screenshots or GIFs (if applicable)**
image

**By submitting this PR, I confirm that:**
- [x] I have reviewed my code and believe it is ready for merging.
- [x] I understand that this PR may be subject to review and changes.
- [x] I agree to abide by the code of conduct and contributing guidelines of this project.

### CODE REVIEW

**Comment by Adimaniac31** [comment]
Can you look into the PR?

**Review by bryanlundberg — CHANGES_REQUESTED** [review]
@Adimaniac31 looks very good the result 👌 But i found a minor issue for mobile also i have some suggestions to improve overall layout.

- Confirm button to the right because its the principal.

Heres a possible UI, you can play with color, sizes, hover, transitions, etc.

image


https://github.com/bryanlundberg/NexusTimer/assets/119996547/9d2bdb51-bd13-4fff-882e-600fb854fa86

**Comment by Adimaniac31** [comment]
Yeah, sure but can you merge this PR till the end of the day if I cannot do the overall layout,since this is my final PR for hacktoberfest.That would mean a lot.

**Comment by bryanlundberg** [comment]
> Yeah, sure but can you merge this PR till the end of the day if I cannot do the overall layout,since this is my final PR for hacktoberfest.That would mean a lot.

I cannot make changes directly because this code is scheduled for production deployment. However, I suggest reviewing the codebase for potential optimizations. Look for opportunities to enhance CSS, remove unnecessary blank spaces, refactor functions, and separate logic from components. I'm ready to quickly merge any improvements you find in 1hr.

@Adimaniac31

**Comment by bryanlundberg** [comment]
I could merge this one if you address fixing the scrolling issue and save the UI rework for another day.

**Comment by Adimaniac31** [comment]
Yeah,sure.
Thanks

**Comment by bryanlundberg** [comment]
> Yeah,sure. Thanks

Not sure, maybe just a overflow hidden at the moment

**Comment by Adimaniac31** [comment]
Hello, I have made the confirmation modal completely fill the height also moved the function to useModalCube.
Also, I will try making improving the UI of the confirmation modal later. Can you merge my PR now?
Thanks.
image

**Review by bryanlundberg — APPROVED** [review]
Thank you! It's working excellently, @Adimaniac31

**Comment by Adimaniac31** [comment]
Thanks for merging!
Also, it was nice working with you. Can we connect on linkedIn?

**Comment by Adimaniac31** [comment]
Hello, can you check if this PR has hacktoberfest-accepted label attached to it?
Sorry, for inconvenience.

**Pull request merged**
